a='python'
# print(a.upper())

# print('python'.upper())
# print('python'.lower())
# print('python'.capitalize())
# print('python'.casefold())
# print('python'.islower())
# print('python'.isupper())
# print('pyTHon'.swapcase())
# print('PYtHon'.swapcase())
# print('pYtHon coDe'.capitalize())
# print('pyTHon coDe'.title()) 
# print('Real Me'.istitle())
# # print('Real me'.istitle())
# print('python program'.startswith('f'))
# print('python program'.startswith('p'))
# print('python program'.startswith('fpy'))
# print('python program'.startswith('fk'))
# print('python'.isspace())
print('python'.find('y'))
print('python'.find('ho'))
print('python'.find('t'))
# print('python program'.endswith('on'))
# print('python program'.endswith('ram'))
# name="hello pooja"
# print(type (name))
